# Generated by Django 5.1.4 on 2025-01-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_created_at_user_role_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('STOREKEEPER', 'StoreKeeper'), ('MANAGER', 'Manager')], default='STOREKEEPER', max_length=12),
        ),
    ]
